### ISSUE TITLE
Cabal deps

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/tidal-bootstrap#6]
Hi this script stopped working for people a few weeks ago. One solution is here:
  http://lurk.org/groups/tidal/messages/topic/2kkap8lbgQrky3992ALIGx/

Another is to install core haskell only.

Would it be OK to move this script / repo into the tidalcycles organisation?

**Comment by davidgranstrom** [comment]
Hi,

Thanks for letting me know about this.

I think that a stack based solution would be nice (it was actually my original intention to use stack, but I wanted to stay with the then recommended approach). However, this causes an issue that you have already adressed in the thread, namely that the atom plugin settings will have to be modified. This could of course be something that the script informs the user about, maybe printing the exact steps that you outline in your post.

Installing the haskell-core only in an automated fashion seems to be harder, as homebrew only seem to package the [haskell-platform](https://www.haskell.org/platform/mac.html#osx-homebrewcask) as a homebrew cask.

The solutions I can see at the moment is:

1) Let the user manually install [haskell-core](https://www.haskell.org/platform/mac.html#osx-none) and remove the `ghc` dependency from the script.

2) Use a stack based approach, modify the script to use `stack` instead of `cabal` and print instructions on how to modify the atom plugin ghci path.

If you think the stack based install will be the recommended approach in the future, I think option 2 would be best.

Unfortunately I will not have the time to do something about this at the moment, but if anyone wants to send a PR that would of course be very welcome. 

And yes, I think it would be a great idea to move this repo into the org! 👍

**Comment by davidgranstrom** [comment]
I just confirmed that by uninstalling `haskell-platform` and installing `haskell-core` manually the script works as intended. Would like try the install procedure again with `haskell-platform` to see if/how it breaks.

**Comment by yaxu** [comment]
Now using ghcup
